# -*- coding: utf-8 -*-
"""TASK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVLFdSoFSaFr0nNA3ncItJdY6YCyPOpV
"""

import re
from datetime import datetime
import pytz
import ipywidgets as widgets
from IPython.display import display, clear_output

def chatbot_response(user_input):
    user_input = user_input.lower()

    if user_input == "bye":
        return "Goodbye! Have a great day."

    elif re.search(r"\b(hello|hi|hey)\b", user_input):
        return "Hello! How can I assist you today?"

    elif re.search(r"\b(how are you|how's it going)\b", user_input):
        return "I'm just a program, but I'm doing great! Hope you're fine too."

    elif re.search(r"\b(your name)\b", user_input):
        return "I'm ChatBotX, your assistant."

    elif re.search(r"\b(time)\b", user_input):

        india_time = datetime.now(pytz.timezone('Asia/Kolkata'))
        current_time = india_time.strftime("%I:%M %p")
        return f"The current time in India is {current_time}."

    elif re.search(r"\b(thank you|thanks)\b", user_input):
        return "You're welcome! Happy to help."

    elif re.search(r"\b(help|assist)\b", user_input):
        return "I can tell you the time, my name, or just chat with you."

    else:
        return "I'm not sure I understand. Can you rephrase?"

text_input = widgets.Text(
    value='',
    placeholder='Type your message here...',
    description='You:',
    disabled=False
)

output = widgets.Output()

conversation_history = []

def handle_input(sender):
    user_message = text_input.value.strip()

    if user_message == '':
        return

    bot_reply = chatbot_response(user_message)

    conversation_history.append(f"You: {user_message}")
    conversation_history.append(f"ChatBot: {bot_reply}")

    with output:
        clear_output(wait=True)

        for line in conversation_history:
            print(line)

    if user_message.lower() == 'bye':
        text_input.disabled = True

    text_input.value = ''

text_input.on_submit(handle_input)

display(text_input, output)

"""You can check the current time of the Colab instance by running this shell command:"""

!date